spring:
  application:
    name: BOARDTEST

  # Jsp View Resolver Setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # MariaDB Setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5705/boardtest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 111111

  # Jpa Setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Context-path Setting
server:
  servlet:
    context-path: /board
    jsp:
      init-parameters:
        development: true

logging:
  level:
    org.hibernate.SQL: debug
